Repository Motonary/Orbit, pull requests merged in 2018-10, with the labels that each got.

#6 Create planet assignment models
  Gemfile
  Gemfile.lock
  app/models/assignment.rb
  app/models/project.rb
  app/models/sub_assignment.rb
  app/models/user.rb
  app/models/users_project.rb
  config/initializers/inflections.rb
  db/migrate/20181022104538_create_assignments.rb
  db/migrate/20181023132357_create_sub_assignments.rb
  db/migrate/20181023132553_remove_column_from_assignments.rb
  db/migrate/20181023135116_create_projects.rb
  db/migrate/20181023135335_create_users_projects.rb
  db/schema.rb
  frontend/src/javascripts/components/main.js
  test/fixtures/assignments.yml
  test/fixtures/projects.yml
  test/fixtures/sub_assignments.yml
  test/fixtures/users.yml
  test/fixtures/users_projects.yml
  test/models/assignment_test.rb
  test/models/project_test.rb
  test/models/sub_assignment_test.rb
  test/models/user_test.rb
  test/models/users_project_test.rb
Labels: enhancement

#8 Create rough top page functions
  app/controllers/api/projects_controller.rb
  app/controllers/api/user_token_controller.rb
  app/controllers/api/users_controller.rb
  app/models/project.rb
  app/models/users_project.rb
  config/puma.rb
  config/routes.rb
  db/migrate/20181023135335_create_users_projects.rb
  db/migrate/20181024054748_create_projects_users.rb
  db/migrate/20181024055157_drop_users_projects_table.rb
  db/migrate/20181024055858_change_column_name_mistake.rb
  db/migrate/20181024083327_remove_column_of_users.rb
  db/schema.rb
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/components/index/main.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/top-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/javascripts/reducers/projects.js
  frontend/src/stylesheets/style.scss
  test/fixtures/users_projects.yml
  test/models/users_project_test.rb
Labels: enhancement

#12 [WIP] Arrange components
  frontend/.eslintrc
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/about_page.js
  frontend/src/javascripts/components/guests/about-page.js
  frontend/src/javascripts/components/guests/guest-only.js
  frontend/src/javascripts/components/guests/login-form.js
  frontend/src/javascripts/components/guests/top-page.js
  frontend/src/javascripts/components/mypage.js
  frontend/src/javascripts/components/top_page.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/top-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/webpack.config.js
Labels: in progress, refactoring

#14 Fix top page (#13)
  app/controllers/api/user_token_controller.rb
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/guests/guest-only.js
  frontend/src/javascripts/components/guests/signin-form.js
  frontend/src/javascripts/components/guests/signup-form.js
  frontend/src/javascripts/components/guests/top-page.js
  frontend/src/javascripts/components/top_page.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/stylesheets/top_page.scss
Labels: refactoring

#18 modify form style
  frontend/src/javascripts/components/guests/signin-form.js
  frontend/src/javascripts/components/guests/signup-form.js
  frontend/src/javascripts/components/guests/top-page.js
  frontend/src/stylesheets/form_field.scss
  frontend/src/stylesheets/top_page.scss
Labels: design

#17 designize my page
  frontend/src/images/main/back_icon.png
  frontend/src/images/main/history_icon.png
  frontend/src/images/main/planet_btn.png
  frontend/src/images/main/planet_holder_btn.png
  frontend/src/images/main/setting_icon.png
  frontend/src/images/main/user_default_icon.png
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/users/delete-icon.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/planet-img.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/common.scss
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/header.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/page_container.scss
  frontend/src/stylesheets/project_page.scss
Labels: design

#32 Add strong parameter
  app/controllers/api/assignments_controller.rb
  app/controllers/api/projects_controller.rb
  app/controllers/api/user_token_controller.rb
  app/models/assignment.rb
  app/models/project.rb
  app/models/sub_assignment.rb
  app/models/user.rb
  db/migrate/20181027023702_change_enum_column_to_string.rb
  db/migrate/20181027032102_rollback_enum_string_columns.rb
  db/schema.rb
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/users/delete-icon.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/planet-img.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/constants.js
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: enhancement

#33 Designize project page
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/project_page.scss
Labels: design

#45 Improve db seed
  app/models/assignment.rb
  app/models/project.rb
  app/models/sub_assignment.rb
  app/models/user.rb
  db/migrate/20181024055157_drop_users_projects_table.rb
  db/migrate/20181028011026_rename_sub_assignments_table_column.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/sub_assignments.yml
  test/fixtures/users.yml
  test/models/sub_assignment_test.rb
  test/models/user_test.rb
Labels: enhancement

#46 Improve header
  Gemfile
  Gemfile.lock
  app/models/assignment.rb
  app/models/project.rb
  app/models/sub_assignment.rb
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/history-page.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/components/users/user-only.js
Labels: enhancement

#50 Redesign Header
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/index/main.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/history-page.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/constants.js
  frontend/src/stylesheets/common.scss
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/header.scss
  frontend/src/stylesheets/history_page.scss
  frontend/src/stylesheets/page_container.scss
  frontend/src/stylesheets/project_page.scss
Labels: design

#49 Optimize api response
  Gemfile
  Gemfile.lock
  app/controllers/api/assignments_controller.rb
  app/models/assignment.rb
  app/models/sub_assignment.rb
  app/models/user.rb
  config/application.rb
  db/migrate/20181029055843_add_columns_to_main_and_sub_assign_ments.rb
  db/migrate/20181029061726_change_column_of_assignments.rb
  db/schema.rb
  db/seeds.rb
  frontend/src/javascripts/actions/assignments.js
  test/fixtures/assignments.yml
  test/fixtures/sub_assignments.yml
  test/models/assignment_test.rb
  test/models/sub_assignment_test.rb
Labels: refactoring

#57 improve revolving assignment data
  app/controllers/api/assignments_controller.rb
  app/models/assignment.rb
  app/models/sub_assignment.rb
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/reducers/assignments.js
Labels: enhancement

#58 Add selecting assignment
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/assignments.js
Labels: enhancement
