Repository Motonary/Orbit, pull requests merged in 2018-11, with the labels that each got.

#55 Improve header routing
  frontend/.eslintrc
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/reducers/assignments.js
  frontend/src/stylesheets/header.scss
Labels: enhancement

#61 Improve Footer Routing
  app/controllers/api/projects_controller.rb
  app/models/assignment.rb
  app/models/project.rb
  config/routes.rb
  db/seeds.rb
  frontend/package-lock.json
  frontend/package.json
  frontend/src/images/footer/delete_btn_1.png
  frontend/src/images/footer/delete_btn_2.png
  frontend/src/images/footer/delete_btn_3.png
  frontend/src/images/footer/planet_holder_btn.png
  frontend/src/images/footer/revival_btn.png
  frontend/src/images/header/back_icon.png
  frontend/src/images/header/history_icon.png
  frontend/src/images/header/setting_icon.png
  frontend/src/images/main/blackhole.png
  frontend/src/images/main/metor.png
  frontend/src/images/main/missile.png
  frontend/src/images/planets/star_4.png
  frontend/src/images/planets_checked/star_10_check.png
  frontend/src/images/planets_checked/star_11_check.png
  frontend/src/images/planets_checked/star_12_check.png
  frontend/src/images/planets_checked/star_13_check.png
  frontend/src/images/planets_checked/star_14_check.png
  frontend/src/images/planets_checked/star_15_check.png
  frontend/src/images/planets_checked/star_1_check.png
  frontend/src/images/planets_checked/star_2_check.png
  frontend/src/images/planets_checked/star_3_check.png
  frontend/src/images/planets_checked/star_4_check.png
  frontend/src/images/planets_checked/star_5_check.png
  frontend/src/images/planets_checked/star_6_check.png
  frontend/src/images/planets_checked/star_7_check.png
  frontend/src/images/planets_checked/star_8_check.png
  frontend/src/images/planets_checked/star_9_check.png
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/actions/common.js
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/modal.js
  frontend/src/javascripts/components/molecules/planet.js
  frontend/src/javascripts/components/molecules/popup-box.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/history-page.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/assignments.js
  frontend/src/javascripts/reducers/common.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/javascripts/reducers/projects.js
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/_popup_balloon.scss
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/project_page.scss
Labels: enhancement

#60 [WIP] Create project bar
  app/controllers/api/projects_controller.rb
  app/models/project.rb
  config/routes.rb
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/javascripts/reducers/projects.js
Labels: In progress, enhancement

#56 Add destroy animation
  frontend/src/javascripts/components/atoms/confirm-btn.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/modal.js
  frontend/src/javascripts/components/molecules/planet.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/stylesheets/confirm_btn.scss
  frontend/src/stylesheets/modal.scss
  frontend/src/stylesheets/project_page.scss
Labels: design, enhancement

#62 Create project bar function
  .gitignore
  app/controllers/api/projects_controller.rb
  app/models/assignment.rb
  app/models/project.rb
  config/routes.rb
  db/seeds.rb
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/assignments.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/javascripts/reducers/projects.js
Labels: enhancement

#64 finalize my page design
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/stylesheets/mypage.scss
Labels: design

#66 create assignment form
  app/controllers/api/assignments_controller.rb
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/actions/common.js
  frontend/src/javascripts/components/molecules/assignment-form.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/common.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/form_balloon.scss
Labels: design, enhancement

#36 Create profile update function
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/users_controller.rb
  app/models/project.rb
  app/models/user.rb
  app/uploaders/avatar_uploader.rb
  app/views/api/users/update_avatar.html.erb
  config/initializers/carrier_wave.rb
  config/routes.rb
  db/migrate/20181027021836_add_avatar_column_to_users.rb
  db/schema.rb
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/profile-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/current-user.js
  frontend/src/stylesheets/header.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/setting_page.scss
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: enhancement

#67 Modify destroy motion
  app/models/project.rb
  frontend/src/javascripts/actions/common.js
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/molecules/assignment-form.js
  frontend/src/javascripts/components/molecules/modal.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/molecules/project-bar.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/common.js
  frontend/src/javascripts/reducers/index.js
Labels: design, enhancement

#85 Install signout button on setting page
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/components/users/profile-page.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/reducers/current-user.js
  frontend/src/stylesheets/form_field.scss
Labels: enhancement

#82 Fix bug on login
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/components/index/main.js
  frontend/src/javascripts/components/molecules/modal.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/constants.js
Labels: bug

#83 Fix bug on project page
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/users/project-page.js
Labels: bug

#89 Create constants folder
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/actions/common.js
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/molecules/planet.js
  frontend/src/javascripts/components/molecules/project-bar.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/history-page.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/constants.js
  frontend/src/javascripts/constants/actiontypes.js
  frontend/src/javascripts/constants/images.js
  frontend/src/javascripts/constants/url.js
  frontend/src/javascripts/reducers/assignments.js
  frontend/src/javascripts/reducers/common.js
  frontend/src/javascripts/reducers/current-user.js
  frontend/src/javascripts/reducers/projects.js
Labels: refactoring

#90 Fix profile updating
  app/controllers/api/users_controller.rb
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/components/users/profile-page.js
Labels: bug

#99 Fix default image path
  app/uploaders/avatar_uploader.rb
  frontend/src/javascripts/constants/images.js
  public/user_default_icon.png
Labels: bug

#108 Prettierの導入
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/javascripts/actions/assignments.js
  frontend/src/javascripts/actions/common.js
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/atoms/confirm-btn.js
  frontend/src/javascripts/components/guests/guest-only.js
  frontend/src/javascripts/components/guests/signin-form.js
  frontend/src/javascripts/components/guests/signup-form.js
  frontend/src/javascripts/components/index/main.js
  frontend/src/javascripts/components/molecules/assignment-form.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/modal.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/molecules/planet.js
  frontend/src/javascripts/components/molecules/popup-box.js
  frontend/src/javascripts/components/molecules/project-bar.js
  frontend/src/javascripts/components/users/footer.js
  frontend/src/javascripts/components/users/header.js
  frontend/src/javascripts/components/users/history-page.js
  frontend/src/javascripts/components/users/mypage.js
  frontend/src/javascripts/components/users/profile-page.js
  frontend/src/javascripts/components/users/project-page.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/javascripts/constants/actiontypes.js
  frontend/src/javascripts/constants/images.js
  frontend/src/javascripts/reducers/assignments.js
  frontend/src/javascripts/reducers/common.js
  frontend/src/javascripts/reducers/current-user.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/javascripts/reducers/projects.js
Labels: enhancement

#100 Improve top page
  frontend/src/images/header/sign_in_button.png
  frontend/src/images/header/sign_up_button.png
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/atoms/buttons/form-submit-btn.js
  frontend/src/javascripts/components/atoms/confirm-btn.js
  frontend/src/javascripts/components/atoms/field.js
  frontend/src/javascripts/components/atoms/top-page-planet.js
  frontend/src/javascripts/components/atoms/toppage-btn.js
  frontend/src/javascripts/components/atoms/toppage-logo.js
  frontend/src/javascripts/components/guests/guest-only.js
  frontend/src/javascripts/components/guests/signin-form.js
  frontend/src/javascripts/components/guests/signup-form.js
  frontend/src/javascripts/components/guests/top-page.js
  frontend/src/javascripts/components/molecules/assignment-form.js
  frontend/src/javascripts/components/molecules/forms/toppage-form.js
  frontend/src/javascripts/components/users/user-only.js
  frontend/src/javascripts/constants/images.js
  frontend/src/stylesheets/top_page.scss
Labels: refactoring
