Repository Motonary/Orbit, pull requests merged in 2018-12, with the labels that each got.

#111 Apply atomic design(atoms, molecules only)
  frontend/src/javascripts/app.js
  frontend/src/javascripts/components/atoms/buttons/confirm-btn.js
  frontend/src/javascripts/components/atoms/buttons/toppage-btn.js
  frontend/src/javascripts/components/atoms/confirm-btn.js
  frontend/src/javascripts/components/atoms/fixed-star-in-list.js
  frontend/src/javascripts/components/atoms/planet.js
  frontend/src/javascripts/components/atoms/popup-box.js
  frontend/src/javascripts/components/atoms/toppage-planet-img.js
  frontend/src/javascripts/components/index/guest-only.js
  frontend/src/javascripts/components/index/user-only.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/forms/assignment-form.js
  frontend/src/javascripts/components/molecules/modal.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/molecules/planet.js
  frontend/src/javascripts/components/molecules/project-bar.js
  frontend/src/javascripts/components/organisms/footer.js
  frontend/src/javascripts/components/organisms/header.js
  frontend/src/javascripts/components/organisms/history-page-main.js
  frontend/src/javascripts/components/organisms/mypage-main.js
  frontend/src/javascripts/components/organisms/profile-page-main.js
  frontend/src/javascripts/components/organisms/project-page-main.js
  frontend/src/javascripts/components/pages/errors/404-not-found.js
  frontend/src/javascripts/components/pages/guests/top-page.js
Labels: design, refactoring

#113 Apply atomic design(organisms, pages only)
  frontend/src/javascripts/components/atoms/buttons/delete-btn.js
  frontend/src/javascripts/components/atoms/buttons/header-back-link.js
  frontend/src/javascripts/components/atoms/buttons/header-left-link.js
  frontend/src/javascripts/components/atoms/buttons/header-right-link.js
  frontend/src/javascripts/components/atoms/buttons/planet-holder-opener.js
  frontend/src/javascripts/components/atoms/buttons/revival-btn.js
  frontend/src/javascripts/components/atoms/buttons/select-avatar-btn.js
  frontend/src/javascripts/components/atoms/buttons/sign-out-btn.js
  frontend/src/javascripts/components/atoms/fixed-star.js
  frontend/src/javascripts/components/atoms/planet.js
  frontend/src/javascripts/components/atoms/user-img.js
  frontend/src/javascripts/components/atoms/user-name.js
  frontend/src/javascripts/components/atoms/welcome-user.js
  frontend/src/javascripts/components/index/user-only.js
  frontend/src/javascripts/components/molecules/avatar-updater.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/delete-buttons-list.js
  frontend/src/javascripts/components/molecules/footer-buttons-list.js
  frontend/src/javascripts/components/molecules/forms/profile-update-form.js
  frontend/src/javascripts/components/molecules/header-link-list.js
  frontend/src/javascripts/components/molecules/mypage-user-info.js
  frontend/src/javascripts/components/molecules/planet-holder-list.js
  frontend/src/javascripts/components/molecules/planet-holder.js
  frontend/src/javascripts/components/organisms/footer.js
  frontend/src/javascripts/components/organisms/header.js
  frontend/src/javascripts/components/organisms/history-page-main.js
  frontend/src/javascripts/components/organisms/mypage-main.js
  frontend/src/javascripts/components/organisms/profile-page-main.js
  frontend/src/javascripts/components/organisms/project-page-main.js
  frontend/src/javascripts/components/pages/users/history-page.js
  frontend/src/javascripts/components/pages/users/mypage.js
  frontend/src/javascripts/components/pages/users/profile-page.js
  frontend/src/javascripts/components/pages/users/project.page.js
  frontend/src/javascripts/constants/images.js
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/setting_page.scss
Labels: design, refactoring

#105 Add function to add project
  app/controllers/api/projects_controller.rb
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/javascripts/actions/projects.js
  frontend/src/javascripts/components/index/user-only.js
  frontend/src/javascripts/components/molecules/forms/project-form.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/organisms/footer.js
  frontend/src/javascripts/components/pages/users/project-page.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/javascripts/reducers/projects.js
  frontend/src/stylesheets/mypage.scss
Labels: bug, emergency

#114 Remove bootstrap
  frontend/dist/index.html
  frontend/src/javascripts/actions/users.js
  frontend/src/javascripts/components/atoms/buttons/confirm-btn.js
  frontend/src/javascripts/components/atoms/buttons/select-user-img-btn.js
  frontend/src/javascripts/components/atoms/field.js
  frontend/src/javascripts/components/index/user-only.js
  frontend/src/javascripts/components/molecules/avatar-updater.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/planet-holder.js
  frontend/src/javascripts/components/molecules/user-img-updater.js
  frontend/src/javascripts/components/organisms/mypage-main.js
  frontend/src/javascripts/components/organisms/project-page-main.js
  frontend/src/javascripts/components/organisms/setting-page-main.js
  frontend/src/javascripts/components/pages/users/setting-page.js
  frontend/src/stylesheets/_button.scss
  frontend/src/stylesheets/common.scss
  frontend/src/stylesheets/confirm_btn.scss
  frontend/src/stylesheets/form_field.scss
  frontend/src/stylesheets/header.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/page_container.scss
  frontend/src/stylesheets/project_page.scss
  frontend/src/stylesheets/setting_page.scss
  frontend/src/stylesheets/top_page.scss
Labels: design, enhancement

#116 Modify selected assignments
  frontend/src/images/planets_checked/star_10_check.png
  frontend/src/images/planets_checked/star_11_check.png
  frontend/src/images/planets_checked/star_12_check.png
  frontend/src/images/planets_checked/star_13_check.png
  frontend/src/images/planets_checked/star_14_check.png
  frontend/src/images/planets_checked/star_15_check.png
  frontend/src/images/planets_checked/star_1_check.png
  frontend/src/images/planets_checked/star_2_check.png
  frontend/src/images/planets_checked/star_3_check.png
  frontend/src/images/planets_checked/star_4_check.png
  frontend/src/images/planets_checked/star_5_check.png
  frontend/src/images/planets_checked/star_6_check.png
  frontend/src/images/planets_checked/star_7_check.png
  frontend/src/images/planets_checked/star_8_check.png
  frontend/src/images/planets_checked/star_9_check.png
  frontend/src/javascripts/components/atoms/planet.js
  frontend/src/javascripts/components/atoms/popup-box.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/forms/project-form.js
  frontend/src/javascripts/components/organisms/footer.js
  frontend/src/javascripts/constants/images.js
  frontend/src/javascripts/reducers/assignments.js
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/_popup_balloon.scss
  frontend/src/stylesheets/destroy_animate.scss
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/form_balloon.scss
  frontend/src/stylesheets/form_field.scss
  frontend/src/stylesheets/project_page.scss
Labels: bug, enhancement

#121 Drap and Drop
  app/models/assignment.rb
  db/migrate/20181207061502_rename_column.rb
  db/schema.rb
  frontend/src/javascripts/components/atoms/buttons/planet-holder-opener.js
  frontend/src/javascripts/components/atoms/field.js
  frontend/src/javascripts/components/atoms/popup-box.js
  frontend/src/javascripts/components/molecules/circle-orbit.js
  frontend/src/javascripts/components/molecules/confirm-modal.js
  frontend/src/javascripts/components/molecules/form-modal.js
  frontend/src/javascripts/components/molecules/forms/assignment-form.js
  frontend/src/javascripts/components/molecules/forms/project-form.js
  frontend/src/javascripts/components/molecules/mypage-orbit.js
  frontend/src/javascripts/components/molecules/planet-holder-list.js
  frontend/src/javascripts/components/molecules/planet-holder.js
  frontend/src/javascripts/components/molecules/planet-list.js
  frontend/src/javascripts/components/organisms/footer.js
  frontend/src/javascripts/reducers/common.js
  frontend/src/javascripts/reducers/index.js
  frontend/src/stylesheets/_button.scss
  frontend/src/stylesheets/common.scss
  frontend/src/stylesheets/field.scss
  frontend/src/stylesheets/form_balloon.scss
  frontend/src/stylesheets/form_field.scss
  frontend/src/stylesheets/form_on_modal.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/project_page.scss
  test/fixtures/assignments.yml
  test/models/assignment_test.rb
Labels: design, enhancement

#124 Modify orbit style
  .rspec
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/assignment.rb
  app/models/user.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  db/seeds.rb
  frontend/src/javascripts/components/molecules/project-bar.js
  frontend/src/javascripts/components/organisms/project-page-main.js
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/_popup_balloon.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/project_bar.scss
  frontend/src/stylesheets/project_page.scss
  lib/exception_notifier.rb
  package.json
  spec/factories.rb
  spec/rails_helper.rb
  spec/requests/assignments_spec.rb
  spec/requests/projects.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  test/controllers/assignments_controller_test.rb
Labels: design, enhancement

#129 Improve RSpec Development
  .gitignore
  Gemfile
  Gemfile.lock
  Guardfile
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: enhancement

#131 install jest, enzyme
  .gitignore
  frontend/.babelrc
  frontend/.eslintrc
  frontend/package.json
  frontend/src/__mocks__/fileMock.js
  frontend/src/__mocks__/fileTransformer.js
  frontend/src/__tests__/atoms/planet-img.test.js
  frontend/src/__tests__/atoms/popup-box.test.js
  frontend/src/javascripts/components/atoms/check-mark.js
  frontend/src/javascripts/components/atoms/planet-img.js
  frontend/src/javascripts/components/atoms/planet.js
  frontend/src/jest.config.js
  frontend/webpack.config.js
Labels: TEST

#136 Remove babel, eslint and install tslint
  frontend/.babelrc
  frontend/.eslintrc
  frontend/package.json
  frontend/src/javascripts/actions/assignments.ts
  frontend/src/javascripts/components/atoms/buttons/delete-btn.tsx
  frontend/src/javascripts/components/atoms/buttons/header-left-link.tsx
  frontend/src/javascripts/components/atoms/buttons/planet-holder-opener.tsx
  frontend/src/javascripts/components/atoms/buttons/sign-out-btn.tsx
  frontend/src/javascripts/components/atoms/input-field.tsx
  frontend/src/javascripts/components/atoms/planet-img.tsx
  frontend/src/javascripts/components/atoms/select-field.tsx
  frontend/src/javascripts/components/index/guest-only.tsx
  frontend/src/javascripts/components/index/main.tsx
  frontend/src/javascripts/components/index/user-only.tsx
  frontend/src/javascripts/components/molecules/circle-orbit.tsx
  frontend/src/javascripts/components/molecules/confirm-modal.tsx
  frontend/src/javascripts/components/molecules/form-modal.tsx
  frontend/src/javascripts/components/molecules/forms/assignment-form.tsx
  frontend/src/javascripts/components/molecules/forms/profile-update-form.tsx
  frontend/src/javascripts/components/molecules/forms/project-form.tsx
  frontend/src/javascripts/components/molecules/forms/toppage-form.tsx
  frontend/src/javascripts/components/molecules/header-link-list.tsx
  frontend/src/javascripts/components/molecules/mypage-orbit.tsx
  frontend/src/javascripts/components/molecules/planet-holder-list.tsx
  frontend/src/javascripts/components/molecules/planet-list.tsx
  frontend/src/javascripts/components/molecules/project-bar.tsx
  frontend/src/javascripts/components/organisms/footer.tsx
  frontend/src/javascripts/components/organisms/history-page-main.tsx
  frontend/src/javascripts/components/organisms/mypage-main.tsx
  frontend/src/javascripts/components/organisms/project-page-main.tsx
  frontend/src/javascripts/components/organisms/setting-page-main.tsx
  frontend/src/javascripts/components/pages/guests/top-page.tsx
  frontend/src/javascripts/components/pages/users/history-page.tsx
  frontend/src/javascripts/components/pages/users/mypage.tsx
  frontend/src/javascripts/components/pages/users/project-page.tsx
  frontend/src/javascripts/components/pages/users/setting-page.tsx
  frontend/src/javascripts/constants/images.ts
  frontend/src/javascripts/reducers/index.ts
  frontend/src/javascripts/reducers/projects.ts
  frontend/tslint.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: emergency, enhancement

#134 modify field design
  frontend/src/javascripts/components/atoms/buttons/toppage-btn.tsx
  frontend/src/javascripts/components/atoms/input-field.tsx
  frontend/src/javascripts/components/atoms/select-field.tsx
  frontend/src/javascripts/components/molecules/forms/assignment-form.tsx
  frontend/src/javascripts/components/molecules/forms/profile-update-form.tsx
  frontend/src/javascripts/components/molecules/forms/project-form.tsx
  frontend/src/javascripts/components/molecules/forms/signin-form.tsx
  frontend/src/javascripts/components/molecules/forms/signup-form.tsx
  frontend/src/javascripts/components/molecules/forms/toppage-form.tsx
  frontend/src/javascripts/components/molecules/toppage-form-container.tsx
  frontend/src/javascripts/components/pages/guests/top-page.tsx
  frontend/src/stylesheets/field.scss
  frontend/src/stylesheets/form_field.scss
  frontend/src/stylesheets/form_on_modal.scss
Labels: bug, design

#122 Finalize destroy animation
  frontend/src/javascripts/actions/assignments.ts
  frontend/src/javascripts/actions/common.ts
  frontend/src/javascripts/actions/users.ts
  frontend/src/javascripts/components/atoms/buttons/action-btn.tsx
  frontend/src/javascripts/components/atoms/buttons/delete-btn.tsx
  frontend/src/javascripts/components/atoms/buttons/planet-holder-opener.tsx
  frontend/src/javascripts/components/atoms/buttons/revival-btn.tsx
  frontend/src/javascripts/components/molecules/blackhole.tsx
  frontend/src/javascripts/components/molecules/circle-orbit.tsx
  frontend/src/javascripts/components/molecules/confirm-modal.tsx
  frontend/src/javascripts/components/molecules/delete-buttons-list.tsx
  frontend/src/javascripts/components/molecules/footer-action-btn-list.tsx
  frontend/src/javascripts/components/molecules/footer-buttons-list.tsx
  frontend/src/javascripts/components/molecules/form-modal.tsx
  frontend/src/javascripts/components/molecules/forms/assignment-form.tsx
  frontend/src/javascripts/components/molecules/forms/profile-update-form.tsx
  frontend/src/javascripts/components/molecules/meteorite.tsx
  frontend/src/javascripts/components/molecules/missile.tsx
  frontend/src/javascripts/components/molecules/mypage-orbit.tsx
  frontend/src/javascripts/components/molecules/revival.tsx
  frontend/src/javascripts/components/organisms/footer.tsx
  frontend/src/javascripts/constants/actiontypes.ts
  frontend/src/javascripts/constants/images.ts
  frontend/src/javascripts/reducers/assignments.ts
  frontend/src/javascripts/reducers/common.ts
  frontend/src/javascripts/reducers/index.ts
  frontend/src/javascripts/reducers/projects.ts
  frontend/src/stylesheets/_button.scss
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/destroy_animate.scss
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/mypage.scss
  frontend/src/stylesheets/project_bar.scss
  frontend/src/stylesheets/project_page.scss
  frontend/tslint.json
Labels: design, emergency, enhancement

#143 Set types to actions
  frontend/src/javascripts/actions/assignments.ts
  frontend/src/javascripts/actions/common.ts
  frontend/src/javascripts/actions/projects.ts
  frontend/src/javascripts/actions/subassignmnets.ts
  frontend/src/javascripts/actions/users.ts
  frontend/src/javascripts/app.tsx
  frontend/src/javascripts/components/atoms/buttons/action-btn.tsx
  frontend/src/javascripts/components/atoms/buttons/header-left-link.tsx
  frontend/src/javascripts/components/atoms/buttons/planet-holder-opener.tsx
  frontend/src/javascripts/components/atoms/buttons/select-user-img-btn.tsx
  frontend/src/javascripts/components/atoms/buttons/sign-out-btn.tsx
  frontend/src/javascripts/components/atoms/input-field.tsx
  frontend/src/javascripts/components/atoms/planet-img.tsx
  frontend/src/javascripts/components/atoms/planet.tsx
  frontend/src/javascripts/components/atoms/select-field.tsx
  frontend/src/javascripts/components/index/main.tsx
  frontend/src/javascripts/components/index/user-only.tsx
  frontend/src/javascripts/components/molecules/blackhole.tsx
  frontend/src/javascripts/components/molecules/circle-orbit.tsx
  frontend/src/javascripts/components/molecules/confirm-modal.tsx
  frontend/src/javascripts/components/molecules/footer-action-btn-list.tsx
  frontend/src/javascripts/components/molecules/form-modal.tsx
  frontend/src/javascripts/components/molecules/forms/assignment-form.tsx
  frontend/src/javascripts/components/molecules/forms/profile-update-form.tsx
  frontend/src/javascripts/components/molecules/forms/project-form.tsx
  frontend/src/javascripts/components/molecules/forms/signin-form.tsx
  frontend/src/javascripts/components/molecules/forms/signup-form.tsx
  frontend/src/javascripts/components/molecules/forms/subassignmnet-form.tsx
  frontend/src/javascripts/components/molecules/header-link-list.tsx
  frontend/src/javascripts/components/molecules/meteorite.tsx
  frontend/src/javascripts/components/molecules/missile.tsx
  frontend/src/javascripts/components/molecules/mypage-orbit.tsx
  frontend/src/javascripts/components/molecules/project-bar.tsx
  frontend/src/javascripts/components/molecules/revival.tsx
  frontend/src/javascripts/components/molecules/toppage-form-container.tsx
  frontend/src/javascripts/components/organisms/footer.tsx
  frontend/src/javascripts/components/organisms/header.tsx
  frontend/src/javascripts/components/organisms/history-page-main.tsx
  frontend/src/javascripts/components/organisms/project-page-main.tsx
  frontend/src/javascripts/components/organisms/setting-page-main.tsx
  frontend/src/javascripts/components/pages/guests/top-page.tsx
  frontend/src/javascripts/components/pages/users/history-page.tsx
  frontend/src/javascripts/components/pages/users/mypage.tsx
  frontend/src/javascripts/components/pages/users/project-page.tsx
  frontend/src/javascripts/components/pages/users/setting-page.tsx
  frontend/src/javascripts/constants/action-types.ts
  frontend/src/javascripts/constants/static-types.ts
  frontend/src/javascripts/reducers/assignments.ts
  frontend/src/javascripts/reducers/common.ts
  frontend/src/javascripts/reducers/current-user.ts
  frontend/src/javascripts/reducers/index.ts
  frontend/src/javascripts/reducers/projects.ts
  frontend/tslint.json
Labels: In progress, enhancement

#149 fix blackhole err
  frontend/src/javascripts/components/molecules/blackhole.tsx
Labels: bug

#145 Finalize histroy page
  app/controllers/api/assignments_controller.rb
  frontend/src/javascripts/components/atoms/planet-img.tsx
  frontend/src/javascripts/components/atoms/planet.tsx
  frontend/src/javascripts/components/molecules/circle-orbit.tsx
  frontend/src/javascripts/components/molecules/confirm-modal.tsx
  frontend/src/javascripts/components/molecules/history-canvas.tsx
  frontend/src/javascripts/components/molecules/planet-list.tsx
  frontend/src/javascripts/components/molecules/planet.tsx
  frontend/src/javascripts/components/molecules/revival.tsx
  frontend/src/javascripts/components/molecules/stored-planet-list.tsx
  frontend/src/javascripts/components/organisms/history-page-main.tsx
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/history_page.scss
Labels: design, emergency, enhancement

#154 add warning function
  frontend/src/javascripts/components/molecules/circle-orbit.tsx
  frontend/src/stylesheets/_orbit_size_initializer.scss
  frontend/src/stylesheets/project_page.scss
Labels: design, enhancement

#165 Fix Restore API
  frontend/src/javascripts/components/molecules/revival.tsx
  frontend/src/stylesheets/_button.scss
Labels: bug, enhancement

#171 set upperlimit to stars
  app/controllers/api/assignments_controller.rb
  app/controllers/api/projects_controller.rb
  frontend/src/javascripts/actions/assignments.ts
  frontend/src/javascripts/actions/projects.ts
Labels: enhancement

#172 Add fixed_star destroy function
  app/models/assignment.rb
  app/models/project.rb
  app/models/sub_assignment.rb
  db/seeds.rb
  frontend/src/javascripts/actions/projects.ts
  frontend/src/javascripts/components/atoms/fixed-star.tsx
  frontend/src/javascripts/components/molecules/fixed-star.tsx
  frontend/src/javascripts/components/molecules/footer-action-btn-list.tsx
  frontend/src/javascripts/components/molecules/meteorite.tsx
  frontend/src/javascripts/components/molecules/missile.tsx
  frontend/src/javascripts/components/molecules/planet-holder-list.tsx
  frontend/src/javascripts/components/molecules/planet-holder.tsx
  frontend/src/javascripts/components/molecules/planet.tsx
  frontend/src/javascripts/components/organisms/footer.tsx
  frontend/src/javascripts/components/organisms/project-page-main.tsx
  frontend/src/javascripts/components/pages/users/history-page.tsx
  frontend/src/javascripts/components/pages/users/mypage.tsx
  frontend/src/javascripts/components/pages/users/project-page.tsx
  frontend/src/javascripts/components/pages/users/setting-page.tsx
  frontend/src/javascripts/constants/action-types.ts
  frontend/src/javascripts/constants/images.ts
  frontend/src/javascripts/constants/static-types.ts
  frontend/src/javascripts/reducers/index.ts
  frontend/src/javascripts/reducers/projects.ts
  frontend/src/stylesheets/footer.scss
  frontend/src/stylesheets/project_page.scss
Labels: enhancement

#174 Modify destory animation
  app/controllers/api/assignments_controller.rb
  app/models/assignment.rb
  frontend/src/javascripts/components/molecules/blackhole.tsx
  frontend/src/javascripts/components/molecules/meteorite.tsx
  frontend/src/javascripts/components/molecules/missile.tsx
Labels: design, enhancement

#176 Fix fixed star type range
  app/controllers/api/users_controller.rb
  db/seeds.rb
  frontend/src/javascripts/actions/users.ts
Labels: bug

#173 Add tutorial
  app/controllers/api/users_controller.rb
  config/routes.rb
  frontend/src/javascripts/actions/users.ts
  frontend/src/javascripts/components/atoms/mypage-tutorial.tsx
  frontend/src/javascripts/components/atoms/projectpage-tutorial.tsx
  frontend/src/javascripts/components/organisms/footer.tsx
  frontend/src/javascripts/components/organisms/modals/confirm-modal.tsx
  frontend/src/javascripts/components/organisms/modals/form-modal.tsx
  frontend/src/javascripts/components/organisms/modals/tutorial-modal.tsx
  frontend/src/javascripts/constants/action-types.ts
  frontend/src/stylesheets/tutorial_modal.scss
Labels: design, enhancement
