Repository Motonary/Orbit, pull requests merged in 2019-01, with the labels that each got.

#182 Fix errors
  frontend/src/javascripts/components/atoms/buttons/sign-out-btn.tsx
  frontend/src/javascripts/components/molecules/circle-orbit.tsx
  frontend/src/javascripts/components/molecules/forms/profile-update-form.tsx
  frontend/src/javascripts/components/molecules/history-canvas.tsx
  frontend/src/javascripts/components/molecules/planet.tsx
  frontend/src/javascripts/reducers/assignments.ts
  frontend/src/stylesheets/history_page.scss
  frontend/src/stylesheets/project_page.scss
Labels: bug

#188 Fix history push bug
  frontend/src/javascripts/components/molecules/footer-action-btn-list.tsx
  frontend/src/javascripts/components/molecules/meteorite.tsx
  frontend/src/javascripts/components/molecules/missile.tsx
Labels: bug

#191 Restrict duplicate select of fixed star and planets
  frontend/src/javascripts/components/molecules/planet.tsx
Labels: bug

#190 Fix assignment reducer
  app/controllers/api/assignments_controller.rb
  frontend/package.json
  frontend/src/javascripts/actions/assignments.ts
  frontend/src/javascripts/reducers/assignments.ts
  frontend/yarn.lock
Labels: bug

#194 Fix typo
  frontend/src/javascripts/actions/assignments.ts
Labels: bug

#197 fix planet undefined error
  frontend/src/javascripts/components/molecules/planet.tsx
Labels: bug, enhancement

#196 fix style for project page
  frontend/src/stylesheets/_assignment_popup.scss
  frontend/src/stylesheets/project_page.scss
Labels: bug, design

#195 modify footer-btns
  frontend/src/javascripts/components/molecules/footer-action-btn-list.tsx
Labels: bug, design
